# STEP 1 Build executable binary
ARG BUILD_IMAGE=golang:alpine
FROM ${BUILD_IMAGE} as builder

# Copy golang source code from the host
WORKDIR /project
COPY ./ ./

# Get dependancies and Build the binary
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .

# STEP 2 Build a small image
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /project

# Copy our static executable binary
COPY --from=builder /project/server .

CMD ["./server"]
